BakeBFlake/Models/OrderDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BakeBFlake.Models
{
    public class OrderDetails
    {
        public Int32 Id { get; set; }
        public Int32 OrderId { get; set; }
        public Int32 PasteryId { get; set; }
        public String PasteryName { get; set; }
        public Decimal Price { get; set; }
        public Int32 Amount { get; set; }
    }
}

BakeBFlake/Controllers/CustomerController.cs
using Repository.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BakeBFlake.Controllers
{
    public class CustomerController : Controller
    {
        //
        // GET: /Customer/

        public ActionResult Index(string id = null, string firstName = null, string lastName = null, string address = null)
        {
            ViewBag.Message = "Customers List";

            id = (id != null && id.Length == 0) ? null : id;
            firstName = (firstName != null && firstName.Length == 0) ? null : firstName;
            lastName = (lastName != null && lastName.Length == 0) ? null : lastName;
            address = (address != null && address.Length == 0) ? null : address;

            var model = new List<Customer>();
            if ((Session["LoginUser"] != null) && (Session["LoginUser"] as Customer).IsAdmin)
            {
                model = Repository.DAL.CustomerDAL.SelectByCriteria(id, firstName, lastName, address);
            }
            //var model = getUsers();

            return View(model);
        }

        private List<Customer> getUsers()
        {
            var user1 = new Customer();
            user1.ID = "123";
            user1.Name = "Ido";
            user1.LastName = "Ganzer";
            user1.Address = "Bla bla 30";
            user1.Phone = "5543253";
            user1.Password = "abcde";
            user1.Prefered = true;
            user1.IsAdmin = true;

            var user2 = new Customer();
            user2.ID = "456";
            user2.Name = "Ido2";
            user2.LastName = "Ganzer2";
            user2.Address = "Bla bla 32";
            user2.Phone = "56785467";
            user2.Password = "fghjf";
            user2.Prefered = false;
            user1.IsAdmin = false;

            var users = new List<Customer>();
            users.Add(user1);
            users.Add(user2);

            return users;
        }

        [HttpPost]
        public ActionResult Edit(Customer customer)
        {
            ViewBag.Message = "Customers List";

            Repository.DAL.CustomerDAL.UpdateCustomer(customer);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(string id)
        {
            //var user1 = new Customer();
            //user1.ID = "123";
            //user1.Name = "Ido";
            //user1.LastName = "Ganzer";
            //user1.Address = "Bla bla 30";
            //user1.Phone = "5543253";
            //user1.Password = "abcde";
            //user1.Prefered = true;
            //user1.IsAdmin = true;

            //var model = user1;
            var model = Repository.DAL.CustomerDAL.GetCustomer(id);

            return View(model);
        }

        public ActionResult Delete(string id)
        {
            Repository.DAL.CustomerDAL.DeleteCustomer(id);
            return RedirectToAction("Index");
        }

    }
}

BakeBFlake/Controllers/OrderController.cs
using Repository.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BakeBFlake.Controllers
{
    public class OrderController : Controller
    {
        public ActionResult Index(bool? isPrefered = null, string id = null, string price = null, string customerId = null, string comments = null)
        {
            ViewBag.Message = "Orders List";

            var orders = new List<Order>();

            int? intId = null;
            bool errorId = false;
            if (id != null)
            {
                try
                {
                    intId = int.Parse(id);
                }
                catch (Exception ex)
                {
                    errorId = true;
                }
            }

            int? intPrice = null;
            bool errorPrice = false;
            if (id != null)
            {
                try
                {
                    intPrice = int.Parse(price);
                }
                catch (Exception ex)
                {
                    errorPrice = true;
                }
            }

            if (!errorPrice && !errorId)
            {

                if (Session["LoginUser"] != null)
                {
                    var cust = Session["LoginUser"] as Customer;
                    if (cust.IsAdmin)
                    {
                        orders = Repository.DAL.OrderdDAL.SelectByCriteria(intId, isPrefered, null, null, intPrice, comments, null, customerId, null);
                    }
                    else
                    {
                        orders = Repository.DAL.OrderdDAL.SelectByCriteria(intId, isPrefered, null, null, intPrice, comments, null, cust.ID, null);
                    }
                }
            }

            //var orders = new List<Order>();
            //var order1 = new Order(DateTime.Now, DateTime.Now, 654, "vfdsvs", Repository.Enum.OrderStatus.Accepted, "6532");
            //orders.Add(order1);

            return View(orders);
        }

        public ActionResult Delete(int id)
        {
            Repository.DAL.OrderdDAL.DeleteOrder(id);
            return RedirectToAction("Index");
        }

        public ActionResult View(int id)
        {
            // get order from repo
            //var orderDetails = new List<OrderDetails>();
            //orderDetails.Add(new OrderDetails() { ID = 1, PasteryId = 2, Pastery = new Pastery() { Name = "Choclate Cake", Price = 19.9, ID = 1 }, TotalAmount = 1 });
            //orderDetails.Add(new OrderDetails() { ID = 1, PasteryId = 2, Pastery = new Pastery() { Name = "Onion Bagel", Price = 19.9, ID = 1 }, TotalAmount = 1 });
            //orderDetails.Add(new OrderDetails() { ID = 1, PasteryId = 2, Pastery = new Pastery() { Name = "Rye Bread", Price = 19.9, ID = 1 }, TotalAmount = 1 });
            //var order = new Order(){ID = 1, OrderDate = new DateTime(2014, 10, 3), Status= Repository.Enum.OrderStatus.InProgress, TotalPrice = 89.90, OrderDetails = orderDetails};
            var order = Repository.DAL.OrderdDAL.SelectByCriteria(id);
            ViewBag.EditOrder = false;
            return View(order);
        }

        public ActionResult Edit(int id)
        {
            // get order from repo
            //var orderDetails = new List<OrderDetails>();
            //orderDetails.Add(new OrderDetails() { ID = 1, PasteryId = 2, Pastery = new Pastery() { Name = "Choclate Cake", Price = 19.9, ID = 1 }, TotalAmount = 1 });
            //orderDetails.Add(new OrderDetails() { ID = 1, PasteryId = 2, Pastery = new Pastery() { Name = "Onion Bagel", Price = 19.9, ID = 1 }, TotalAmount = 1 });
            //orderDetails.Add(new OrderDetails() { ID = 1, PasteryId = 2, Pastery = new Pastery() { Name = "Rye Bread", Price = 19.9, ID = 1 }, TotalAmount = 1 });
            //var order = new Order() { ID = 1, OrderDate = new DateTime(2014, 10, 3), Status = Repository.Enum.OrderStatus.InProgress, TotalPrice = 89.90, OrderDetails = orderDetails };
            var order = Repository.DAL.OrderdDAL.SelectByCriteria(id)[0];
            ViewBag.EditOrder = true;
            Session["CurrentOrder"] = order;
            return View(order);
        }

        public bool RemoveItem(int id)
        {
            var order = (Order)Session["CurrentOrder"];
            var item = order.OrderDetails.Find(x => x.ID == id);
            order.OrderDetails.Remove(item);
            return true;
        }

        [HttpPost]
        public ActionResult Save(FormCollection collection)
        {
            var model = (Order)Session["CurrentOrder"];
            try
            {
                TryUpdateModel(model);
                Repository.DAL.OrderdDAL.UpdateOrder(model);
            }
            catch (Exception e)
            {

            }
            Session["CurrentOrder"] = null;
            return RedirectToAction("View", new { id = model.ID });
        }

    }
}

BakeBFlake/Controllers/PasteryController.cs
using Repository.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BakeBFlake.Controllers
{
    public class PasteryController : Controller
    {

        public ActionResult View(int id)
        {
            // get item from repo by id
            var model = Repository.DAL.PastryDAL.GetPatry(id);
            //var model = new Pastery() { ID = 4, Name = "Choclate Cake", Price = 9.99, ImageLink = "http://www.localfranchiseopportunities.net/images/food-franchise-opportunities/food-franchise-opportunities-wyoming.jpg" };
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            // get item from repo by id
            //var model = new Pastery() { ID = 4, Name = "Choclate Cake", Price = 9.99, Type = Repository.Enum.PastryType.Cupcakes, ImageLink = "http://www.localfranchiseopportunities.net/images/food-franchise-opportunities/food-franchise-opportunities-wyoming.jpg" };
            var model = Repository.DAL.PastryDAL.SelectByCriteria(id);
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            var model = new Pastery();
            try
            {
                TryUpdateModel(model, collection);
                int id = Repository.DAL.PastryDAL.AddNewPastry(model);
                return RedirectToAction("View", new { id = id });

            }
            catch (Exception e)
            {
                return RedirectToAction("Create");
            }
            
        }

        [HttpPost]
        public ActionResult Save(FormCollection collection)
        {
            var model = new Pastery();
            try
            {
                UpdateModel(model);
                Repository.DAL.PastryDAL.UpdatePastry(model);
            }
            catch (Exception e)
            {

            }

            return RedirectToAction("View", new { id = model.ID });
        }

    }
}

BakeBFlake/Views/Shared/OrderDetails.cshtml
@model Repository.Models.Order

<table class="table">
    <thead>
        <tr>
            <td>Name</td>
            <td>Amount</td>
            <td>Total Price</td>
            @if (Model.ID == 0 || (bool)ViewBag.EditOrder) { 
            <td>Actions</td>
            }
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.OrderDetails)
    {
        <tr id="@item.ID">
            <td>@item.Pastery.Name</td>
            <td>@item.TotalAmount</td>
            <td id="amount">@(item.TotalAmount * item.Pastery.Price)</td>
            @if (Model.ID == 0 || (bool)ViewBag.EditOrder) {
            <td><button class="btn remove-item">X</button></td>
            }
        </tr>
    }
    </tbody>
</table>

BakeBFlake/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/modernizr")
        @RenderSection("PageScripts", false)
    </head>
    <body>
        <header>
            <div>
                <div class="">
                    <ul class="nav nav-pills">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li data-counter="@Session["ItemsInCart"]" id="cartDisplay">@Html.ActionLink("Cart (" + Session["ItemsInCart"] + ")", "Index", "Cart")</li>

                        @if (Session["LoginUser"] != null) 
                        {
                            <li hidden=@ViewBag.isLoggedIn>@Html.ActionLink("Orders", "Index", "Order")</li>
                            
                            
                            if ((Session["LoginUser"] as Repository.Models.Customer).IsAdmin)
                            { 
                                <li>@Html.ActionLink("Customers", "Index", "Customer")</li>
                                <li>@Html.ActionLink("Create New", "Create", "Pastery")</li>
                            }

                            <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Login", "Login", "Home")</li>
                        }
                        
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li></li>
                    </ul>
                </div>
                <div class="pull-left logo-header">
                    <img src="~/Images/bakelogo.jpg" />
                </div>
            </div>
        </header>
        <div id="body" style="padding-top:250px">
            <section class="container-fluid clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="container">
                <div class="pull-left">
                    <p>&copy; @DateTime.Now.Year Bake N' Flake Backery Shop</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>